#!/usr/bin/env python3

project='ntruprime'
primitives = ['sntrup653', 'sntrup761', 'sntrup857', 'sntrup953', 'sntrup1013', 'sntrup1277']

helpstr = "'''\n"
with open('README.md') as f:
    helpstr += f.read()
helpstr += "'''\n"

with open(f'src/{project}/__init__.py', 'w') as f:
    f.write(helpstr)
    f.write('\n')
    for primitive in primitives:
        f.write(f'from .kem import {primitive}\n')
